package com.nouros.hrms.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

/**
* Auto-generated by:
* org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
*/
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
@Entity
@Table(name="COMPENSATION_STRUCTURE")
public class CompensationStructure extends BaseEntitySaaS{
@Basic
@Column(name="ANNUAL_BONUS_FROM")
private Double annualBonusFrom;

@Basic
@Column(name="ANNUAL_BONUS_TO")
private Double annualBonusTo;

@Basic
@Column(name="ANNUAL_SALARY_RANGE_FROM")
private Double annualSalaryRangeFrom;

@Basic
@Column(name="ANNUAL_SALARY_RANGE_TO")
private Double annualSalaryRangeTo;

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name="DEPARTMENT_ID", columnDefinition="INT")
private Department department;

@GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
@Id
@Column(columnDefinition="INT")
private Integer id;

@Size(max = 200)
@Basic
@Column(name="LIFE_INSURANCE_PACKAGES", length=200)
private String lifeInsurancePackages;

@Basic
@Column(columnDefinition="ENUM", length=3)
private String lti;

@Basic
@Column(name="RETIREMENT_PLAN", columnDefinition="ENUM", length=3)
private String retirementPlan;

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name="ROLE_ID", columnDefinition="INT")
private Designation roleId;

@Size(max = 200)
@Basic
@Column(length=200)
private String title;

@Basic
@Column(name="WORKSPACE_ID", columnDefinition="INT")
private Integer workspaceId;


public CompensationStructure() {
}

public CompensationStructure(Integer id) {
this.id = id;
}

public Double getAnnualBonusFrom() {
return annualBonusFrom;
}

public void setAnnualBonusFrom(Double annualBonusFrom) {
this.annualBonusFrom = annualBonusFrom;
}

public Double getAnnualBonusTo() {
return annualBonusTo;
}

public void setAnnualBonusTo(Double annualBonusTo) {
this.annualBonusTo = annualBonusTo;
}

public Double getAnnualSalaryRangeFrom() {
return annualSalaryRangeFrom;
}

public void setAnnualSalaryRangeFrom(Double annualSalaryRangeFrom) {
this.annualSalaryRangeFrom = annualSalaryRangeFrom;
}

public Double getAnnualSalaryRangeTo() {
return annualSalaryRangeTo;
}

public void setAnnualSalaryRangeTo(Double annualSalaryRangeTo) {
this.annualSalaryRangeTo = annualSalaryRangeTo;
}

public Department getDepartment() {
return department;
}

public void setDepartment(Department department) {
this.department = department;
}

public Integer getId() {
return id;
}

public void setId(Integer id) {
this.id = id;
}

public String getLifeInsurancePackages() {
return lifeInsurancePackages;
}

public void setLifeInsurancePackages(String lifeInsurancePackages) {
this.lifeInsurancePackages = lifeInsurancePackages;
}

public String getLti() {
return lti;
}

public void setLti(String lti) {
this.lti = lti;
}

public String getRetirementPlan() {
return retirementPlan;
}

public void setRetirementPlan(String retirementPlan) {
this.retirementPlan = retirementPlan;
}

public Designation getRoleId() {
	return roleId;
}

public void setRoleId(Designation roleId) {
	this.roleId = roleId;
}

public String getTitle() {
return title;
}

public void setTitle(String title) {
this.title = title;
}

public Integer getWorkspaceId() {
return workspaceId;
}

public void setWorkspaceId(Integer workspaceId) {
this.workspaceId = workspaceId;
}
}
